type TTeams = {
  [key: string]: string;
};

export const TEAMS: TTeams = {
  ATL: 'ATL',
  BKN: 'BKN',
  BOS: 'BOS',
  CHA: 'CHA',
  CHI: 'CHI',
  CLE: 'CLE',
  DAL: 'DAL',
  DEN: 'DEN',
  DET: 'DET',
  GSW: 'GSW',
  HOU: 'HOU',
  IND: 'IND',
  LAC: 'LAC',
  LAL: 'LAL',
  MEM: 'MEM',
  MIA: 'MIA',
  MIL: 'MIL',
  MIN: 'MIN',
  NOP: 'NOP',
  NYK: 'NYK',
  OKC: 'OKC',
  ORL: 'ORL',
  PHI: 'PHI',
  PHX: 'PHX',
  POR: 'POR',
  SAC: 'SAC',
  SAS: 'SAS',
  TOR: 'TOR',
  UTA: 'UTA',
  WAS: 'WAS',
  NBA: 'NBA',
};

export const TEAM_NAMES: TTeams = {
  ATL: 'Hawks',
  BKN: 'Nets',
  BOS: 'Celtics',
  CHA: 'Hornets',
  CHI: 'Bulls',
  CLE: 'Cavaliers',
  DAL: 'Mavericks',
  DEN: 'Nuggets',
  DET: 'Pistons',
  GSW: 'Warriors',
  HOU: 'Rockets',
  IND: 'Pacers',
  LAC: 'Clippers',
  LAL: 'Lakers',
  MEM: 'Grizzlies',
  MIA: 'Heat',
  MIL: 'Bucks',
  MIN: 'Timberwolves',
  NOP: 'Pelicans',
  NYK: 'Knicks',
  OKC: 'Thunder',
  ORL: 'Magic',
  PHI: '76ers',
  PHX: 'Suns',
  POR: 'Trail Blazers',
  SAC: 'Kings',
  SAS: 'Spurs',
  TOR: 'Raptors',
  UTA: 'Jazz',
  WAS: 'Wizards',
  NBA: 'NBA',
};

export const TEAM_ABBR: TTeams = Object.entries(TEAM_NAMES).reduce(
  (acc, [abbr, name]) => ({
    ...acc,
    [name]: abbr,
  }),
  {},
);
